#!/usr/bin/env bash
set -euo pipefail

mode="${1:-test}"
go_bin="${GO:-go}"
test_tags="${TEST_TAGS:-sqlite_omit_load_extension}"
root="$(cd -- "${BASH_SOURCE[0]%/*}/.." && pwd -P)"
cd "$root"
round9_counted_mock_module="integration/round9countedmock"

safe_packages=(
  ./cmd/cyber-abuse-guard
  ./cmd/development-adversarial-v11-prep-validator
  ./cmd/development-public-jailbreak-patterns-v1-validator
  ./cmd/round9-development-benign-corpus-runner
  ./cmd/round9-development-corpus-freezer
  ./cmd/round9-paired-malicious-corpus-freezer
  ./cmd/round9-paired-malicious-corpus-runner
  ./cmd/round9-public-corpus-validator
  ./internal/audit
  ./internal/buildinfo
  ./internal/config
  ./internal/extract
  ./internal/explanation
  ./internal/fixturepublish
  ./internal/plugin
  ./internal/round9corpus
  ./internal/round8test
  ./internal/rules
  ./internal/subject
  ./rules
)
for package in "${safe_packages[@]}" ./internal/classifier; do
  if ! "$go_bin" list -tags="$test_tags" "$package" >/dev/null; then
    printf 'required Round6 safe package is missing or unloadable: %s\n' "$package" >&2
    exit 1
  fi
done

join_regex() {
  local joined="" name
  for name in "$@"; do
    joined+="${joined:+|}${name}"
  done
  printf '^(%s)$' "$joined"
}

require_reviewed_entries() {
  local package="$1" label="$2" discovery_pattern="$3" listed name
  shift 3
  local -A reviewed=()
  for name in "$@"; do
    if [[ -v reviewed["$name"] ]]; then
      printf 'duplicate safe %s allowlist entry: %s\n' "$label" "$name" >&2
      exit 1
    fi
    reviewed["$name"]=0
  done
  listed="$(
    "$go_bin" test -tags="$test_tags" "$package" \
      -list "$discovery_pattern"
  )"
  while IFS= read -r name; do
    [[ "$name" =~ ^(Test|Fuzz|Benchmark|Example)[A-Za-z0-9_]*$ ]] || continue
    if [[ ! -v reviewed["$name"] ]]; then
      printf 'unclassified safe %s entry: %s\n' "$label" "$name" >&2
      exit 1
    fi
    reviewed["$name"]=1
  done <<<"$listed"
  for name in "$@"; do
    if [[ "${reviewed[$name]}" != 1 ]]; then
      printf 'required safe %s entry is missing: %s\n' "$label" "$name" >&2
      exit 1
    fi
  done
}

# Fifth-round extractor audit regressions are safe development tests. Keep an
# explicit name allowlist so renaming or accidentally dropping one fails closed
# before the broader safe-package run.
expected_round5_extract_entries=(
  TestExtractRawPartsToolTransactionSharesPartBudget
  TestExtractRequestConflictingMediaMarkersAreOrderInvariant
  TestExtractRequestInheritedMediaKindUsesChildExplicitMarker
  TestExtractTextToolTransactionSharesPartBudget
  TestRound5LargeTopLevelToolDefinitionsRemainInspectableWithoutRoleIndex
)
round5_extract_pattern="$(join_regex "${expected_round5_extract_entries[@]}")"
listed_round5_extract_tests="$(
  "$go_bin" test ./internal/extract \
    -list "$round5_extract_pattern"
)"
for name in "${expected_round5_extract_entries[@]}"; do
  if ! grep -Fxq "$name" <<<"$listed_round5_extract_tests"; then
    printf 'required safe round-five extractor entry is missing: %s\n' "$name" >&2
    exit 1
  fi
done

# Percent-decoding remediation must retain complete semantic inspection for
# reversible placeholder collisions, the fail-closed malformed-token path, and
# ordinary environment-variable/percent negative controls. Keep these exact
# public synthetic tests in the development allowlist so a later rename or
# accidental deletion cannot silently reopen the bypass.
expected_percent_decode_entries=(
  TestDecodeMixedValidAndInvalidPercentEscapesCompletely
  TestDecodeMarksTokenInternalMalformedPercentEscapeIncomplete
  TestDecodeTextDataURLWithMalformedPercentEscapesIsIncomplete
  TestDecodeTextDataURLWithPercentPlaceholdersIsComplete
  TestDecodePercentEscapesPreservesOrdinaryPercentSyntax
  TestDecodeClosedPercentPlaceholderCollisionsRemainComplete
  TestDecodeUnclosedDoublePercentCollisionRemainsIncomplete
  TestExtractTextDoublePercentEncodedWordCollisionIsComplete
  TestDecodePercentPlaceholderVariablesDoNotProduceBinaryViews
  TestDecodeOversizedUnchangedPercentPlaceholdersRemainComplete
  TestDecodeMalformedSuffixCannotHideInvalidUTF8EncodedPrefix
  TestDecodeSparseHTMLAndModuloPercentSyntaxRemainsComplete
  TestDecodeDensePercentEscapesOverBudgetIsIncomplete
  TestDecodeBinaryPercentEscapeUsesCanonicalSeparator
  TestDecodePercentPerformanceAcceptanceLinux
  BenchmarkDecodeBoundedPercentPaths
)
require_reviewed_entries ./internal/extract "percent-decoding remediation" \
  '^(TestDecodeMixedValidAndInvalidPercentEscapesCompletely|TestDecodeMarksTokenInternalMalformedPercentEscapeIncomplete|TestDecodeTextDataURLWithMalformedPercentEscapesIsIncomplete|TestDecodeTextDataURLWithPercentPlaceholdersIsComplete|TestDecodePercentEscapesPreservesOrdinaryPercentSyntax|TestDecodeClosedPercentPlaceholderCollisionsRemainComplete|TestDecodeUnclosedDoublePercentCollisionRemainsIncomplete|TestExtractTextDoublePercentEncodedWordCollisionIsComplete|TestDecodePercentPlaceholderVariablesDoNotProduceBinaryViews|TestDecodeOversizedUnchangedPercentPlaceholdersRemainComplete|TestDecodeMalformedSuffixCannotHideInvalidUTF8EncodedPrefix|TestDecodeSparseHTMLAndModuloPercentSyntaxRemainsComplete|TestDecodeDensePercentEscapesOverBudgetIsIncomplete|TestDecodeBinaryPercentEscapeUsesCanonicalSeparator|TestDecodePercentPerformanceAcceptanceLinux|BenchmarkDecodeBoundedPercentPaths)$' \
  "${expected_percent_decode_entries[@]}"

# Round8 added public, synthetic-only audit/provenance/router regressions. These
# packages are still executed in full below; this reviewed list additionally
# fails closed if a required production-FP or privacy contract is renamed or
# dropped. No restricted evaluation, retired holdout, or private fixture is
# compiled or inspected here.
expected_round8_audit_entries=(
  TestRound8AuditReadRejectsInvalidPersistedEvent
  TestRound8DecisionExplanationReadAcceptsInternallyConsistentSQLiteRewrite
  TestRound8DecisionExplanationReadRejectsCrossFieldInconsistentSQLiteRow
  TestRound8DecisionExplanationRejectsCrossFieldContradictions
  TestRound8DecisionExplanationRejectsUnsafeOrUnboundedMetadata
  TestRound8DecisionExplanationRejectsUnknownHardFloorReasonAfterJSONDecode
  TestRound8DecisionExplanationValidationCloneAndRoundTrip
  TestRound8RawCaptureCanonicalAliasesHashAndRedactionMetadata
  TestRound8RawCaptureDeduplicatesWithinTTLAndRenewsAtBoundary
  TestRound8RawCaptureDeduplicatesWithoutPersistingRequestHash
  TestRound8RawCaptureReadRejectsMalformedPersistedRows
  TestRound8RawCaptureWriteValidationKeepsPriorityEvent
  TestRound8StatsRetryWindowSemantics
  TestRound8StatsSeparateEventsUniqueRepeatsAndUnhashed
  TestRound8StatsUsesSingleSnapshotDuringConcurrentWrites
  TestV3DatabaseMigratesThroughRawCaptureSchemaV5
  TestV4MigrationRejectsMalformedRawCaptureBeforePublishingBackup
  TestV4RawCaptureMigrationKeepsFirstLiveCaptureAndCreatesPartialUniqueRawSHAIndex
  TestV4RawCaptureMigrationReplaysV5TTLWindowsAndPreservesEventAssociation
  TestV5ContractFailureRollsBackSchemaVersionAndCaptureDeduplication
)
expected_round8_extract_entries=(
  TestRound8ContentKindNamesAreClosed
  TestRound8Exact16KiBAnd300KiBStreamingTextPlacement
  TestRound8ExactProtocolTextPartCounts
  TestRound8FencedCodeProtocolMatrix
  TestRound8FencedLanguageKindsAndPlainFallback
  TestRound8FencedPlannerCrossesDecoderChunks
  TestRound8FencedSegmentationBudgetAbortsBeforePartialField
  TestRound8FencedSegmentationUsesExactAlignedChunkBudget
  TestRound8FencedSyntaxPreservesSystemDeveloperAndHistoryMetadata
  TestRound8FencesCannotCrossSiblingJSONStrings
  TestRound8IndependentToolCallsHaveIsolatedScopes
  TestRound8MultipartTextFieldsHaveIndependentScopes
  TestRound8ProtocolTurnScopeAndSchemaMatrix
  TestRound8ToolCallAndResultContentKindMatrix
)
expected_round8_plugin_entries=(
  TestAuditDecisionExplanationHonorsIdentifierLoggingPolicy
  TestAuditDecisionExplanationIsBoundedAndTextFree
  TestAuditDecisionExplanationMapsEnforcementScopeClosed
  TestRound8BalancedRouterSeededPairedMutationMatrix
  TestRound8BalancedRouterSyntheticProductionFalsePositivePairs
  TestRound8ChatAndResponsesToolSchemaContamination
  TestRound8ClassifierDecisionExplanationPersistsEndToEnd
  TestRound8DecisionExplanationRequiresClassifierOwnedTopLevelCategory
  TestRound8DecisionExplanationUsesClosedEvidenceDimensionMapping
  TestRound8FencedContentKindRouterProtocolMatrix
  TestRound8FencedLogConfigAndUnclosedRouterBoundary
  TestRound8P1FalsePositiveBoundariesAcrossOpenAIProtocols
  TestRound8RouterHistoricalReactivationBoundary
  TestRound8RoleAwareWrapperScorePersistsAcrossNonUserSegments
  TestRound8SystemFencedEvidenceIsNotAnActiveDirective
)
require_reviewed_entries ./internal/audit "round-eight audit" \
  '^(TestRound8[A-Za-z0-9_]*|TestV3DatabaseMigratesThroughRawCaptureSchemaV5|TestV4MigrationRejectsMalformedRawCaptureBeforePublishingBackup|TestV4RawCaptureMigrationKeepsFirstLiveCaptureAndCreatesPartialUniqueRawSHAIndex|TestV4RawCaptureMigrationReplaysV5TTLWindowsAndPreservesEventAssociation|TestV5ContractFailureRollsBackSchemaVersionAndCaptureDeduplication)$' \
  "${expected_round8_audit_entries[@]}"
require_reviewed_entries ./internal/extract "round-eight extractor" '^TestRound8' "${expected_round8_extract_entries[@]}"
require_reviewed_entries ./internal/plugin "round-eight plugin" '^(TestRound8|TestAuditDecisionExplanation)' "${expected_round8_plugin_entries[@]}"

# Round9's candidate-bound eligibility, disposition separation, audit schema v6,
# and direct-current-user extraction tests are public synthetic development
# entries. Prefix-wide discovery keeps new Round9 tests fail-closed; the exact
# non-Round9 names below are reviewed migration and cross-layer regressions that
# were added by the same redesign.
expected_round9_audit_entries=(
  TestClassifierProofBudgetIncompleteReasonIsValid
  TestEnforcementScopeLegacyCurrentUserV2JSONAndEventRemainReadable
  TestEnforcementScopePersistedMutationFailsClosed
  TestEnforcementScopePersistsThroughQueryAndExportsWithoutRequestText
  TestEnforcementScopeRejectsEmptyUnknownAndMismatchedEligibleExplanations
  TestEnforcementScopeValidationAndJSONContract
  TestV5MigrationRejectsDecisionExplanationPrivacyBypassBeforeBackup
  TestV4MigrationBackupIsExactBeforeV6RawCaptureCleanup
  TestRound9V5ToV6MigrationIsAtomic
  TestRound9V5ToV6MigrationCreatesPreMigrationBackup
  TestRound9V6ReadsV5RowsAsLegacyUnspecified
  TestRound9DecisionExplanationRejectsUnknownAndContradictoryEligibility
  TestRound9DecisionKindRejectsMasqueradingBlockExplanations
  TestRound9EligibleMaliciousAuditHasDistinctDecisionKind
  TestRound9DecisionExplanationV2CanonicalizesEmptyCollections
  TestRound9DecisionExplanationV2UnionRoundTrip
  TestRound9DecisionExplanationV2RejectsUnknownAndCrossBranchFields
  TestRound9DecisionKindQueryStatsAndExports
  TestRound9StatsRejectsUnknownPersistedDecisionKind
  TestRound9AuditRejectsRequestLikeTopLevelRuleID
  TestRound9RawCaptureMetadataAndUnknownSourceBlockSurviveRestart
  TestRound9WALRestartQuickCheckAndOldSOSchemaGate
  TestRound9MigrationBackupsAreVisibleAndRequireSeparateCleanup
  TestRound9MigrationBackupCleanupRejectsSymlinkArtifacts
)
expected_round9_extract_entries=(
	BenchmarkRound9ToolAssociationPlanning
  TestRound9DirectUserProfilesSeparateCurrentInputFromAuthorityAndTools
  TestRound9MediaPromptProfilesMarkOnlyExactPromptAsCurrentUser
  TestRound9AlphaSearchQueriesAreCurrentButScopeIndependent
  TestRound9DirectUserProfileAliasesRemainIncomplete
  TestRound9OnlyTerminalHistoryUserCanBeCurrent
  TestRound9OpenAIToolResultAssociationRequiresUniquePriorCall
  TestRound9ProviderToolResultAssociationContract
  TestRound9StructuredToolResultAuthorityBudgetTruncationFailsClosed
  TestRound9StructuredToolResultAuthorityDoesNotCrossTerminalTransactionBoundary
  TestRound9StructuredToolResultAuthorityFailsClosedAndDoesNotPartiallyCommit
  TestRound9StructuredToolResultAssociationDistinguishesReferableAndMalformedTransactions
  TestRound9StructuredToolResultTextLeavesAreAtomicAndProviderExact
  TestRound9ToolAssociationFieldNamesRemainVisibleOutsideClosedProviderObjects
  TestRound9GeminiDuplicateWrappersFailClosed
  TestRound9GeminiExplicitToolAssociationRequiresMatchingNames
  TestRound9GeminiWrapperMultiplicityIsScopedPerPart
  TestRound9OpenAIChatToolAssociationRequiresCanonicalFunctionShape
  TestRound9ProviderToolAssociationTransactionsAreAdjacentAndComplete
  TestRound9ResponsesToolAssociationRequiresExactSubtype
  TestRound9ToolAssociationAuthorityUsesExactProviderTextPath
  TestRound9ToolAssociationDuplicateKeysFailClosed
)
expected_round9_plugin_entries=(
  TestClassifierProofBudgetIncompleteDispositionContract
  TestInspectionDispositionIncompleteOverridesMaliciousPrefix
  TestInspectionDispositionCompleteMaliciousTextStillBlocksBalanced
  TestInspectionDispositionEligibleStandaloneMetaBlocksWithoutSubjectEvaluation
  TestInspectionDispositionMetaAmplifiedBaseWinnerStillEvaluatesSubject
  TestInspectionDispositionEligibleMaliciousTextUsesDistinctAuditKind
  TestInspectionDispositionBareActionBlockCannotBecomeMaliciousTextBlock
  TestInspectionDispositionContradictoryEligibleFlagFailsClosed
  TestInspectionDispositionForgedEligibleResultCannotBecomeMaliciousTextBlock
  TestInspectionDispositionMalformedEligibleWinnerFailsClosed
  TestInspectionDispositionMaliciousTextBlockOutranksSubjectRisk
  TestInspectionDispositionNonMaliciousBlockKindsAreTaxonomyIsolated
  TestInspectionDispositionOpaqueAuditUsesAuditDecisionKind
  TestInspectionDispositionCleanAllowSkipsSubjectEvaluation
  TestInspectionDispositionCompleteOpaqueMediaAuditDoesNotHideTextBlock
  TestFourRepositoryRequestLocalAuthorityAndInertCarrierBoundaries
  TestManagementAuditEndpointsDistinguishDisabledFromUnavailable
  TestAuthorizationPolicyCannotCreateOrRemoveMaliciousEligibility
  TestRound9EligibleStandaloneMetaBlockRetainsWinnerWithoutSubjectRisk
  TestRound9ManagementDisclosesAndDoubleConfirmsMigrationBackupCleanup
  TestRound9ManagementMigrationBackupInventoryWorksButPurgeFailsClosedWithAuditDisabled
  TestRound9PublicRunnerDefensiveQuotedAmbiguityFullRouteRegression
  TestRound9RequestLocalToolBlockPersistsEndToEnd
  TestIncidentResponseRoleMatrix
  TestNERVExplicitIntentRoutesBlockAcrossRolesAndTransports
  TestNERVProviderLongSystemAndTerminalToolRoutesBlock
  TestNERVNeutralAndDefensiveRequestsRouteUpstream
  TestProviderToolAuthorityRoutingContract
  TestProviderToolAuthorityRoutePersistsCanonicalAuditFields
  TestProviderStructuredToolAuthorityCompositionBoundary
  TestRequestLocalStandaloneMetaTakeoverRoutesBlockBatchAndStream
  TestRequestLocalMetaQuotedConcealmentDoesNotRouteBlock
  TestRequestLocalToolResultRequiresUniqueMatchingTerminalCall
  TestRound6LongText270KiBActiveRolePositionMatrixBlocks
  TestAuthenticatedRequestLocalSystemBlocksWithoutPoisoningCleanFollowUp
  TestToolPayloadMetadataNamedFieldsDoNotCreateCurrentUserEligibility
  TestAdjacentNegationProofBudgetCannotCreateRolelessMaliciousEligibility
  TestLargeTopLevelToolDefinitionDoesNotCreateBlockingEligibility
  TestRequestInterceptorPhishingTrainingTelemetryRealCredentialMatrix
  TestRequestInterceptorPhishingTrainingTelemetryTransferVerbMatrix
  TestRequestInterceptorDefensiveQuotedSystemDeveloperBoundary
  TestRequestInterceptorStrictFailsClosedOnTokenInternalMalformedPercentEscape
  TestRequestInterceptorMalformedTextDataURLUsesModePolicy
  TestRequestInterceptorLongPercentPlaceholdersRemainComplete
  TestRequestInterceptorPercentPlaceholderCollisionBlocksSemantically
  TestRequestInterceptorClassifierProofBudgetUsesModePolicyAndAudit
)
require_reviewed_entries ./internal/audit "round-nine audit" \
  '^(TestRound9[A-Za-z0-9_]*|TestClassifierProofBudgetIncompleteReasonIsValid|TestEnforcementScope[A-Za-z0-9_]*|TestV5MigrationRejectsDecisionExplanationPrivacyBypassBeforeBackup|TestV4MigrationBackupIsExactBeforeV6RawCaptureCleanup)$' \
  "${expected_round9_audit_entries[@]}"
require_reviewed_entries ./internal/extract "round-nine extractor" \
	'^(Test|Benchmark)Round9[A-Za-z0-9_]*$' "${expected_round9_extract_entries[@]}"
require_reviewed_entries ./internal/plugin "round-nine plugin" \
  '^(TestRound9[A-Za-z0-9_]*|TestClassifierProofBudgetIncompleteDispositionContract|TestInspectionDisposition[A-Za-z0-9_]*|TestFourRepositoryRequestLocalAuthorityAndInertCarrierBoundaries|TestManagementAuditEndpointsDistinguishDisabledFromUnavailable|TestAuthorizationPolicyCannotCreateOrRemoveMaliciousEligibility|TestIncidentResponseRoleMatrix|TestNERVExplicitIntentRoutesBlockAcrossRolesAndTransports|TestNERVProviderLongSystemAndTerminalToolRoutesBlock|TestNERVNeutralAndDefensiveRequestsRouteUpstream|TestProviderToolAuthorityRoutingContract|TestProviderToolAuthorityRoutePersistsCanonicalAuditFields|TestProviderStructuredToolAuthorityCompositionBoundary|TestRequestLocalStandaloneMetaTakeoverRoutesBlockBatchAndStream|TestRequestLocalMetaQuotedConcealmentDoesNotRouteBlock|TestRequestLocalToolResultRequiresUniqueMatchingTerminalCall|TestRound6LongText270KiBActiveRolePositionMatrixBlocks|TestAuthenticatedRequestLocalSystemBlocksWithoutPoisoningCleanFollowUp|TestToolPayloadMetadataNamedFieldsDoNotCreateCurrentUserEligibility|TestAdjacentNegationProofBudgetCannotCreateRolelessMaliciousEligibility|TestLargeTopLevelToolDefinitionDoesNotCreateBlockingEligibility|TestRequestInterceptorPhishingTrainingTelemetryRealCredentialMatrix|TestRequestInterceptorPhishingTrainingTelemetryTransferVerbMatrix|TestRequestInterceptorDefensiveQuotedSystemDeveloperBoundary|TestRequestInterceptorStrictFailsClosedOnTokenInternalMalformedPercentEscape|TestRequestInterceptorMalformedTextDataURLUsesModePolicy|TestRequestInterceptorLongPercentPlaceholdersRemainComplete|TestRequestInterceptorPercentPlaceholderCollisionBlocksSemantically|TestRequestInterceptorClassifierProofBudgetUsesModePolicyAndAudit)$' \
  "${expected_round9_plugin_entries[@]}"

# Round10 production-hardening tests are public synthetic regressions. Keep the
# extractor and plugin prefixes closed so a renamed or newly added test cannot
# silently bypass the reviewed development/race boundary.
expected_round10_extract_entries=(
  TestRound10ControlEscapesCannotSplitWordsInsideLargeSparseSource
  TestRound10DecodedVariantBudgetExactBoundaries
  TestRound10DerivedLocalDecodeWindowPreservesFencedFieldMetadata
  TestRound10DistinctSparseExplanationsOverBudgetRemainIncomplete
  TestRound10InvalidUTF8CompletenessDoesNotDependOnFieldPadding
  TestRound10InvalidUTF8PercentEscapesRemainIncomplete
  TestRound10IdenticalSparseDecodeWindowsRetainActiveContentKindAndBlock
  TestRound10OversizedBase64SourceRemainsFailClosed
  TestRound10OversizedEncodingProbeDoesNotCopySource
  TestRound10ProviderToolResultAssociationDistinguishesReferableAndTerminal
  TestRound10ReferableToolResultAssociationFailsClosedAtNewBoundary
  TestRound10RepeatedSparseWindowViewsConsumeGlobalVariantBudget
  TestRound10RoleAmbiguousTerminalItemCannotCreateReferableAssociation
  TestRound10SourceBoundedLargeDerivedViewsStreamCompletely
  TestRound10SparseMixedBinaryPercentEscapesExposeCanonicalText
  TestRound10SparsePrefixCannotHideWholeBase64Envelope
  TestRound10SparseRecoveryCannotClearNestedDataURLLayerLimit
  TestRound10SplitDecodedViewPreservesUTF8BoundaryOverlap
  TestRound10ToolResultAssociationKeepsExistingNumericValues
)
expected_round10_plugin_entries=(
  TestRound10ByteAccountingMismatchHasDedicatedReason
  TestRound10ClassifierCoverageReasonsUseOneExactBucket
  TestRound10ColocatedToolResultUserTextIsAmbiguityBarrier
  TestRound10CompatibilityTotalsDoNotCollapseCoverageReasons
  TestRound10CompleteCoverageDoesNotIncrementReasonCounters
  TestRound10CompleteNonsemanticBlockDoesNotCountSemanticBlock
  TestRound10CoverageDimensionCountersAreConcurrentAndRaceSafe
  TestRound10CoverageDimensionKeysAreFixedAndRequestIndependent
  TestRound10CoverageDimensionsAccountBoundedSinkChunks
  TestRound10CoverageLogicalFieldIDNamespaceInvariant
  TestRound10CoverageLogicalPartsDoNotSplitAcrossContentPieceOrdinals
  TestRound10CoverageFailuresAreCrossDimensionAttributable
  TestRound10CoverageObservationStorageIsFixedAndBounded
  TestRound10CoveragePositionDoesNotInventBackForUnterminatedField
  TestRound10CoverageReasonCountersAreConcurrentAndFixed
  TestRound10CoverageSnapshotsStayRequestConsistentDuringConcurrentCommits
  TestRound10DecidedEarlyReturnsCommitFinalDisposition
  TestRound10EarlyFailureSnapshotsStayStableAndConcurrent
  TestRound10ExtractorCoverageReasonsUseBoundedStageBuckets
  TestRound10FinalDispositionCommitIsAtomicUnderConcurrentSnapshots
  TestRound10FinalDispositionProjectionDoesNotMutateWinnerOrCategory
  TestRound10FinalDispositionSeparatesIncompleteFailClosedFromSemanticBlock
  TestRound10FinalDispositionSeparatesSemanticWinnerFromModeAction
  TestRound10GeminiTerminalWrapperAttemptsBlockHistoricalFallback
  TestRound10HistoricalToolUserFollowupAllowsInertAndUnprovenRelations
  TestRound10HistoricalToolUserFollowupBlocksBeforeUpstream
  TestRound10IncompleteDispositionDoesNotMutateSemanticWinner
  TestRound10LinuxPerformanceGate
  TestRound10OperationalCoverageReasonsSeparateTimeoutFromExtractorSink
  TestRound10OversizedRPCUsesAtomicCoverageCommit
  TestRound10PerformanceGateContract
  TestRound10ProductionRouteCoverageDimensionsReconcileCompleteAndIncomplete
  TestRound10RecoveredRouterErrorDoesNotCommitCandidateFinalDisposition
  TestRound10SinkAndTimeoutFailuresEnterUnifiedCoverageDenominator
  TestRound10StrictUnknownSourceUsesAtomicCoverageCommit
  TestRound10SubjectRiskBlockCountsCompleteNonsemanticDisposition
  TestRound10TolerantUnknownSourcesCommitFinalDispositionAfterClassification
  TestRound10UnclassifiedRuntimeFailuresCommitFinalDisposition
)
require_reviewed_entries ./internal/extract "round-ten extractor" \
  '^TestRound10[A-Za-z0-9_]*$' "${expected_round10_extract_entries[@]}"
require_reviewed_entries ./internal/plugin "round-ten plugin" \
  '^TestRound10[A-Za-z0-9_]*$' "${expected_round10_plugin_entries[@]}"

expected_round8_classifier_entries=(
	TestRound8ActiveCredentialNounsAloneAreNotHostileConflicts
	TestRound8AmbiguousPayloadPersistenceDoesNotImplyMalware
  TestRound8CompleteNonUserDirectiveRemainsDetectable
  TestRound8CredentialMetadataDoubleNegationCannotClaimNoSecretAccess
  TestRound8CredentialMetadataHarvestDoesNotImplyTheft
  TestRound8CredentialMetadataMarkersCannotSuppressCRED002
  TestRound8CredentialMetadataMarkersCannotSuppressSecretHarvest
  TestRound8CredentialMetadataMayNameNegatedSecretExamples
  TestRound8CredentialMetadataNeighborStillBlocksHostileHarvest
  TestRound8CredentialMetadataNegatedHostileVerbDoesNotCancelSafety
  TestRound8CredentialMetadataSafetyCannotCoverCoordinatedSecretCollection
  TestRound8CredentialMetadataSlashSeparatedSecretExamplesRemainNegated
  TestRound8CredentialTheftActionRequiresWordBoundary
  TestRound8CoreFamilyRoleTurnAndProvenanceMatrix
  TestRound8CurrentTurnOwnershipAndHistoricalReactivation
  TestRound8DirectCarrierTraversesEveryUncancelledAnchor
  TestRound8DirectCarrierProofOverflowIsUnavailable
  TestRound8AffirmativeCarrierProofOverflowIsUnavailable
  TestRound8Exact16KiBAnd300KiBClassifierPlacement
  TestRound8GenericDevelopmentVocabularyStress
  TestRound8HardFloorReasonIsEmptyWhenFloorIsNotApplied
  TestRound8HardFloorReasonTracksActualAdmissionPath
  TestRound8HistoricalAndCurrentToolCallOwnership
  TestRound8NearestHistoricalReferentBoundary
  TestRound8ManagedHealthHelperDoesNotImplyMalware
  TestRound8ManagedHealthHelperNeighborStillBlocksBackdoor
  TestRound8ManagedHealthHelperPerformanceLanguageDoesNotImplyMalware
  TestRound8NewerBenignInertScopeTerminatesOlderBareReferent
	TestRound8OutcomeCandidateHasCompleteAuditExplanation
	TestRound8OAuthAuthenticationWorkflowsDoNotCreateHostileCredentialConflict
	TestRound8UnrelatedNegationCannotActivateAdjacentOAuthHardBlock
	TestRound8ApprovedCredentialStoreWorkflowsRemainBenign
	TestRound8OAuthWorkflowMarkersCannotWashOutCredentialTheft
	TestRound8OwnedOAuthBackendTransferRemainsBenign
	TestRound8OwnedOAuthApprovedStoreAfterAuthenticationRemainsBenign
	TestRound8CredentialWorkflowMarkersDoNotSuppressRuleTargets
	TestRound8CredentialTheftCoreSynonymsRemainBlocked
	TestRound8PossessiveBrowserTargetsDistinguishConsentFromAcquisition
	TestRound8OwnedOAuthResponseExtractionIsNotCredentialTheft
  TestRound8ProfiledWrapperRoleCapKeepsBatchAndStreamExplanationsConsistent
  TestRound8ProfiledLongDefensiveQuoteReferentReactivation
  TestRound8QuotedOrInertSuppressedExplanation
  TestRound8SameDirectiveCrossesWindowButSeparateMessagesDoNotCompose
  TestRound8SeededOneSlotPairedMutationMatrix
  TestRound8SemanticCorePredicateCapsIncompleteCandidates
	TestRound8SelfContainedCarrierKeepsInertAndDescriptiveBoundaries
	TestRound8SelfContainedCurrentCarrierCannotSplitCoreAcrossAdjacentFences
  TestRound8StreamingMetadataOwnership
  TestRound8StreamingSemanticPotentialUsesCorePredicateAndDynamicThreshold
  TestRound8SyntheticProductionFalsePositivePairs
  TestRound8SyntheticWinningRuleIDsRemainAuditable
  TestRound8OverflowLedgerUsesRealRiskAndPhysicalOrder
  TestRound8RoleAwareWrapperCapReconcilesOwnershipAndHardFloor
)

expected_round9_classifier_entries=(
  TestPublicRunnerDefensiveQuotedReviewIsSuppressed
  TestPublicRunnerDefensiveQuotedReviewReactivationBlocks
  TestPublicRunnerDefensiveQuotedReviewAmbiguityFailsClosed
  TestRound9PublicRunnerDefensiveQuotedReviewProfiledStreamingParity
  TestDefensiveQuotedReviewStructuredAuditVariants
  TestDefensiveQuotedReviewStructuredBenignRequestsRemainNormal
  TestDefensiveQuotedReviewStructuredVariantsRejectIndependentExecution
  TestDefensiveQuotedReviewStructuredReferentBudgetFailsClosed
  TestRunesMayContainNegationHandlesInternalHardBoundary
  TestEligibleMaliciousWinnerRequiresContainedRuleAndEligibilityParity
  TestRoleAwareNonUserBaseBehaviorRemainsAuditOnlyAfterWrapperCap
  TestRoleAwareHistoricalAbuseDoesNotOverrideCurrentBenignRequest
  TestStreamingHistoricalAbuseDoesNotOverrideCurrentBenignRequest
  TestRoleAwareActiveSystemAbuseBlocksWithoutPromotingOtherNonUserRoles
  TestRoleAwareProviderToolPayloadIsAuditedButCannotBlock
  TestRoleAwareNonUserOperationalOverrideRemainsAuditOnly
  TestRound9ClaudeTerminalToolResultWithColocatedUserTextBatchStreamingParity
  TestRound9ClaudeToolResultBeforeLaterUserItemRemainsHistorical
  TestRound9HistoricalNonUserGroupBoundaryRemainsInert
  TestRound9NonterminalSplitToolResultRemainsInert
  TestRound9NonterminalToolGroupBoundaryRemainsInert
  TestRound9ProfiledGroupBoundaryBatchStreamingParity
  TestRound9ProfiledGroupBoundaryProvenBenignEvictionRemainsComplete
  TestRound9ProtocolToolCallScopeIsolationAndUntrustedAdmission
  TestRound9RequestLocalSplitCoreIncomplete
  TestRound9RequestLocalSystemFencedCarrierBatchStreamingParity
  TestKeysmithRequestLocalSystemAndToolMiddleBackBlock
  TestKeysmithRequestLocalCarrierAuthorityBoundaries
  TestRound9SelfContainedCurrentCarrierRequiresNaturalLanguageExecutionOwner
  TestRound9UnindexedNonterminalToolResultRemainsHistorical
  TestRound9UnindexedTerminalToolResultUsesMaxTurnBatchStreamingParity
  TestRound9ActorBoundEligibility
  TestRound9MultiFieldUnboundOccurrenceCannotBorrowFinalFieldOwnership
  TestRound9ProfiledWinnerIdentityBindsScopeClauseAndOccurrences
  TestRound9EqualScoreCandidatesDoNotMergeWinnerEvidence
  TestRound9MaliciousTextProducerInventoryClosure
  TestRound9ModeActionsDoNotBypassEligibility
  TestRound9EligibleWinnerOutranksHigherIneligibleRisk
  TestRound9AdjacentNegationOverflowIsIncompleteNotMalicious
  TestRuleIntentNegationFastGateCoversASCIIMarkers
  TestIndependentMaliciousExecutionBoundaryPrefilterClosure
  TestRound9IndependentMaliciousClauseIsNotWashedByAnalysisPrefix
  TestRound9SemanticOwnerCarriesPostposedDefensiveConstraint
  TestRound9SemanticOwnerConstraintDoesNotCoverLaterIndependentMalice
  TestRound9CategoryPositiveMaliceCoversHostileAcquisitionAndEvasion
  TestRound9AmbiguousAcquisitionVerbsDoNotCreateHostileCredentialScope
  TestRound9BareCredentialTheftVerbDoesNotProveHostileScope
  TestRound9IdentityNarrowingRecomputesAction
  TestRound9ActiveMetaOverrideRequiresCurrentTrustedUser
  TestRound9QuotedMetaAnalysisAndOrdinaryLocalWorkStayNonBlocking
  TestRound9BoundedRefusalSuppressionRequiresStrongSameScopeComposition
  TestRound9LongActiveMetaOverrideWithoutAdjacentCarrierRemainsClassifiable
  TestRound9GeneratedAgentExtendedWindowIsTrustedCurrentUserOnly
  TestRound9GeneratedAgentQuotedTailBeyondExtendedWindowCannotLendSuppression
  TestRound9GeneratedAgentExtendedWindowPerformanceAcceptance
  TestCandidateRichMaxPartsAllocationBound
  TestCandidateRichProfiledMaxPartsPerformanceBound
  TestRound9ProfiledSyntheticMetaEvidenceKeepsGroupOwnerCoordinates
  TestRound9ProfiledMetaControlCarrierCompositionRespectsLocalOwner
  TestRound9MetaWrapperDoesNotSuppressIndependentMaliciousClause
  TestQuotedSafetyReviewSpanContentStripsOnlyKnownFenceInfoStrings
  TestHistoricalUserSafetyReviewReferentBatchStreamingParity
  TestHistoricalReviewGroupContaminationCannotPromoteBareReferent
  TestHistoricalReviewEvictionCannotEraseDisqualifyingField
  TestHistoricalNonUserPayloadCannotAcquireBareReferentAuthority
  TestRound9EncodedCurrentUserCarriersRemainBlocking
  TestPlainHistoricalAttackRefusalBareFollowUpDoesNotReactivate
  TestRound9HistoricalAssistantCannotBecomeBareReferent
  TestRound9BareReferentDoesNotReactivateHistoricalCarrierContentKinds
  TestRound9HistoricalToolResultCannotBecomeBareReferent
  TestRound9ToolSchemaCannotBecomeReferent
  TestRound9CurrentNaturalLanguageQuoteUsesExplicitLocalReferent
  TestRound9ResponsesSingleFieldQuotedReviewContinuationParity
  TestRound9StreamingProfiledEligibilityParity
  TestRound9StreamingIncompleteCannotRetainMaliciousWinner
  TestRound9StreamingStandaloneMetaWhollyInsideLaterPhysicalWindowRemainsEligible
  TestStreamingRequestLevelProfiledModeMatchesBatchForLegacyAssistant
  TestPredeclaredProfiledStreamingNormalizesEarlierLegacyField
  TestLateProfiledAutoDetectionIsExplicitlyIncomplete
  TestRound6StreamingUntrustedFallbackPreservesIncompleteProofBudget
  TestRound6StreamingRolelessStructuralMetadataRequiresExplicitAuthority
  TestRound6StreamingExactUnknownAuditDoesNotSuppressLongRiskSuffix
  TestRound6StreamingUntrustedOverSixtyFourFailsClosedWithoutRetainingText
  TestMatcherOccurrenceBudgetDeduplicatesStandardAndCompactViews
  TestMatcherOccurrenceBudgetOverflowsOnlyForNewPhysicalProof
  TestSignalOccurrenceLookupUsesFullPhysicalIdentity
  TestSignalOccurrenceLookupComparesKeysAfterHashCollision
  TestOverflowSemanticOnlyNegatedTailPreservesAccumulatedAssessment
  TestOverflowSemanticOnlyNegatedTailInvariant
  TestRound9PersistentTrustedMetaBlockHasTruthfulExplanation
  TestRound9OperationalAuditLogDestructionRequiresAllAxes
  TestRound9AuditLogMaintenanceNearNeighborsRemainNonBlocking
  TestRound9OperationalAuditLogDestructionRemainsBlockable
  TestRound9InertLabeledLogAndUnclosedFenceDoNotBlock
  TestInertLabeledCarrierCannotMaterializeEligibleExplicitCandidates
  TestRound9CandidateIdentityProofCannotBeForgedOrRewritten
  TestRound9TransformativeAnalyticalOwnerBindsQuotedPayload
  TestRound9TransformativeAnalyticalOwnerBindsOnlyImmediatePayload
  TestRound9ExplicitMaliciousRelationsAreCategoryLocal
  TestRound9ExplicitMaliciousRelationsRejectBenignNearNeighbors
  TestRound9ExplicitMaliciousRelationIsCategoryFallback
  TestRound9ExplicitMaliciousRelationRejectsNegatedAndFloodInputs
  TestRound9ExplicitMaliciousFallbackDoesNotComposeAcrossClauses
  TestRound9ExplicitMaliciousFallbackBindsIndependentClause
  TestRound9DefensiveArtifactActionsRemainBoundToTheArtifact
  TestRound9ClauseLocalDestructiveDataRelation
  TestRound9ExplicitMaliciousRelationOverflowPositions
  TestRound9ExplicitMaliciousRelationOverflowUsesOnlyAdjacentSoftWindows
  TestRound9ExplicitMaliciousRelationOverflowRetainsSoftChainAxes
  TestRound9ExplicitMaliciousRelationOverflowTaxonomyDominanceIsSoftChainLocal
  TestRound9ExplicitMaliciousRelationOverflowHonorsWholeFieldOwners
  TestRound9ExplicitMaliciousRelationOverflowBatchStreamingParity
  TestRound9PairedMaliciousCorpusCISamplesBlockWithoutBenignRegression
  TestRound9TelemetrySolicitationCannotHideBehindTrainingEvents
  TestRound9DefensiveAlertMaintenanceDoesNotBecomeEvasion
  TestRound9RequestLocalDefensiveQuoteRoleParity
  TestDefensiveQuotedReferentExistingOwnerDisposition
  TestDefensiveQuotedReferentOwnerParityBatchStreaming
  TestDefensiveQuotedReferentOwnerLocalityBatchStreaming
  TestRequestLocalSystemCarrierCancellationStaysFieldLocalBatchStreaming
  TestRound9ExplicitRelationTypedAxesHavePhysicalOccurrences
  TestRound9ExplicitRelationRejectsUnownedEligibilityAxisOccurrence
  TestEligibilityEvasionActionObjectHostilePurposeMatrix
  TestNERVEvasionRuleVocabularyRolePositionBatchStreamingMatrix
  TestEligibilityEvasionSOCMaintenanceRecoveryBoundaries
  TestEligibilityDetectionArtifactHostileSameClauseMatrix
  TestEligibilityPassivePhishingReportsRemainNonExecutingAcrossRoles
  TestEligibilityPassivePhishingIndependentReactivationBlocksAcrossRoles
  TestEligibilityClosedLogCarrierReactivationBlocksAcrossRoles
  TestEligibilityLabeledCarrierPayloadControlsRemainInertAcrossRoles
  TestEligibilityLabeledCarrierExplicitExecutionTailReactivatesAcrossRoles
  TestEligibilityLabeledCarrierIndependentMaliciousTailReactivatesAcrossRoles
  TestEligibilityLabeledCarrierNearMatchesDoNotSuppressAcrossRoles
  TestLabeledCarrierProofBudgetOverflowPreservesOwnerAcrossRoles
  TestLabeledCarrierCoordinatedTailScanHasBoundedCost
  TestEligibilityPhishingIntentFloodLinearPerformance
  TestEligibilityLongIntentOnlyPlaceholderFloodRemainsComplete
  TestExplicitRelationProofBudgetNeverBecomesCompleteAllow
  TestExplicitRelationProofWindowSeamsNeverBecomeCompleteAllow
  TestCompletePhishingRelationPredicateHasBoundedCost
  TestExplicitRelationLongBenignControlsRemainComplete
  TestExplicitRelationProofBudgetDoesNotJoinIndependentBenignClauses
  TestExplicitRelationProofBudgetDoesNotJoinNoSpaceBenignCarrier
  TestExplicitRelationProofWindowDoesNotCrossStrongScopeBoundary
  TestExplicitRelationProofBudgetNoSpacePeriodStartsNewStrongScope
  TestExplicitRelationProofBudgetPreservesNoSpaceMaliciousCarrier
  TestExplicitRelationProofBudgetAcrossFieldsRemainsIncomplete
  TestExplicitRelationProofBudgetIndependentScopeOrderRemainsIncomplete
  TestExplicitRelationProofWindowsAreUTF8Safe
  TestExplicitRelationLongDefensivePrefixCannotLaunderHostileConflict
  TestLinkedPhishingRealCredentialVictimDoesNotBroadenBenignScopes
  TestPhishingRealCredentialRelationsDefeatSyntheticTrainingScope
  TestPhishingTrainingTelemetryTransferVerbRoleBatchStreamingMatrix
  TestPhishingRealCredentialRelationSafeBoundaries
  TestPhishingRealCredentialRelationBoundaryAndMixedTargetRegressions
  TestPhishingDetectorPrefixRealCredentialVerbReactivation
  TestPhishingRealCredentialRelationPlacementAndReactivation
  TestPhishingPairedCurrentSpeechActParaphrasesBlockWithoutBenignRegression
  TestPhishingRealCredentialRelationPreservesTakeoverClassification
  TestPhishingRealCredentialRelationPreservesStoredCredentialTheftClassification
  TestRound9CurrentUserMetaAndQuotedReferentRemainBlockable
  TestRound9ExplicitRelationHonorsCandidateLocalDefensiveOwner
  TestRound9DefensiveOwnerCannotLaunderStrongHostileConflict
  TestRound9QuotedActivationRequiresOneCompleteCarrier
  TestRound9QuotedActivationVerbInsideCarrierCannotSelfActivate
  TestRound9EncryptedBackupAdjectiveDoesNotBecomeRansomware
  TestRound9RansomwareRequiresOwnedDestructiveAction
	TestRound9MalwareCreationBindsItsDirectArtifact
  TestExplicitMalwareControlSurvivesDefensiveDetectorTarget
  TestRound9DevelopmentGeneralizationReview
  TestRound9QuotedInstructionCarrierGrammar
  TestIncidentResponseNaturalDefensiveReviewGrammar
  TestIncidentResponseContinuationLastEffectiveState
  TestIncidentResponseSameClauseAlternativeCancellationState
  TestIncidentResponsePerspectiveAndBoundaryFailClosed
  TestDevelopmentPrepChineseDefenseEvasionWrapperBlocks
  TestDevelopmentPrepChineseDefenseEvasionBenignNeighborsRemainNonBlocking
  TestNERVCarrierMatrixLongFieldPositionsBatchStreamingParity
  TestNERVCarrierMatrixProviderLongSystemAndTerminalToolPositions
  TestNERVCarrierMatrixBenignNearNeighborsRemainNonBlocking
  TestNERVActivationCarrierArchetypeRoleModeBatchStreamingMatrix
  TestNERVActivationCarrierAloneAndBenignPairsRemainNonBlocking
  TestNERVChunkParentToChildGroundTruthProviderMatrix
  TestNERVChunkNonUserOverflowStreamingRepresentatives
  TestNERVExplicitIntentRoleBatchStreamingMatrix
  TestNERVNamesDocumentationAndDefensiveReviewRemainNonBlocking
  TestRound9RequestLocalSystemCarrierKindMatrix
  TestRound9RequestLocalSystemCarrier512BoundaryBatchStreamingParity
  TestRound9RequestLocalSystemCarrierBeyondWindowIsExplicitlyIncomplete
  TestRound9RequestLocalSystemCarrierStreamingCancellationIsProvisional
  TestRound9RequestLocalSystemCarrierStreamingScopeClosureCommits
  TestRound9RequestLocalStandaloneMetaTakeoverBatchStreamingParity
  TestRound9RequestLocalMetaTakeoverFalsePositiveBoundaries
  TestRound9RequestLocalSystemIncidentResponseTransactionBatchStreamingParity
  TestRound9RequestLocalSystemIncidentResponseIsolation
  TestRound9RequestLocalToolAuthorityRequiresUniqueMatchingCall
  TestRound9ProviderToolAuthorityContractMatrix
  TestRound9StreamingSegmentAdaptersPreserveTerminalMetadata
)

expected_round10_classifier_entries=(
  BenchmarkRound10ProfiledIndependentWindowRecovery
  TestRound10CompleteWindowBlockDoesNotEraseLaterReferentOverflow
  TestRound10CurrentUserCodeCarrierMarkerRemainsInert
  TestRound10DirectCompactionCarrierBeforeApplicationIsIncomplete
  TestRound10DirectCompactionLogicalFieldIdentityAndLifecycle
  TestRound10DirectCompactionNonCurrentProviderUnitIsBarrier
  TestRound10DirectCompactionProcessesEveryRunAndLaterPipelines
  TestRound10DirectCompactionRejectsMixedRuleInertCarriers
  TestRound10DirectCompactionTrueBatchFieldwiseBytewiseProtocolParity
  TestRound10DirectCompactionWindowBoundariesAndIndependentWinner
  TestRound10HistoricalToolActivationNearWindowPositionsParity
  TestRound10HistoricalToolResultRequiresExplicitAdjacentCurrentUserActivation
  TestRound10LaterSameFieldCancellationRevokesRecoveredActivation
  TestRound10LongActivationPreflightCaseFold
  TestRound10LongActivationRecoveryNeverReplacesOrdinaryWinner
  TestRound10ManyCodeBlocksDoNotTurnLargeREADMEIntoIncompleteReferent
  TestRound10OversizedActivationCannotReturnCompleteClean
  TestRound10ProfiledActivationOffsetAndByteBoundary
  TestRound10ProfiledBatchInputCoverageBoundaries
  TestRound10ProfiledContinuationDecisionCapIsFailClosed
  TestRound10ProfiledIndependentWindowRecoveryAcceptsClosedActivationPrefixes
  TestRound10ProfiledIndependentWindowRecoveryAcrossPositions
  TestRound10ProfiledIndependentWindowRecoveryActivationFloodIsNearLinear
  TestRound10ProfiledIndependentWindowRecoveryChargesClassificationBudget
  TestRound10ProfiledIndependentWindowRecoveryEnforcesByteLimit
  TestRound10ProfiledIndependentWindowRecoveryHonorsCarrierBoundary
  TestRound10ProfiledIndependentWindowRecoveryHonorsQuotesAndCancellation
  TestRound10ProfiledIndependentWindowRecoveryPreservesHistoricalToolOwnership
  TestRound10ProfiledIndependentWindowRecoveryRejectsArbitraryActivationOwner
  TestRound10ProfiledIndependentWindowRecoverySkipsLongBenignTextWithoutCharge
  TestRound10ProfiledRangeOutsideStructuredQuotesUsesExactRuneEnd
  TestRound10ProfiledStructuredQuoteIndexBoundsSingleQuoteFlood
  TestRound10ProtocolHistoricalToolActivationRequiresActionAndReferent
  TestRound10ProtocolHistoricalToolAmbiguityBarriersBatchStreamingParity
  TestRound10PublicCompactDirectCurrentUserBlocksAcrossProductionScanners
  TestRound10PublicCompactQuotedAndDefensiveHistoryRemainNonBlocking
  TestRound10ReferableHistoricalToolAloneRemainsInert
  TestRound10RecoveredActivationCrossFieldCancellationParity
  TestRound10RecoveredActivationCrossWindowCancellationOrder
  TestRound10RecoveredActivationWinnerIsOrderIndependentAcrossFields
  TestRound10RecoveredAndIndependentOrdinaryWinnersRankIdentically
  TestRound10RequestLocalSystemOverflowDefersUntilIndependentWinner
  TestRound10SameScopeCompleteBlockCannotCloseUnknownReferentOverflow
  TestRound10ScopedPendingProofRequiresExactScopeAndFieldWinner
  TestRound10StreamingFieldIDCannotBeReusedAfterClose
  TestRound10TerminalToolPendingProofRequiresExactFieldWinner
  TestRound10TwoPendingFieldsRequireMoreThanOneFieldWinner
)

expected_round12_classifier_entries=(
  TestRound12CarrierOmissionRecomputesGroupClassificationFlags
  TestRound12CrossScopeBareReferentDoesNotReactivateOuterDefensiveOwner
  TestRound12ExactUntrustedCrossWindowOpenerIsUnavailable
  TestRound12ExactUntrustedManyFenceShapeStreaming
  TestRound12ExactUntrustedMalformedWrappersRestorePendingWinner
  TestRound12ExactUntrustedOuterDefensiveProtocolMatrix
  TestRound12ExactUntrustedProofBudgetOverflowIsUnavailable
  TestRound12ExactUntrustedPureNaturalFieldParity
  TestRound12ExactUntrustedRawStructuralProofRejectsMalformedTags
  TestRound12MDXV45ActivatedProtocolMatrix
  TestRound12MDXV45FalsePositiveBoundaries
  TestRound12MDXV45FamiliesCannotCrossScope
  TestRound12MDXV45LeadingFamiliesStaySourceSpecific
  TestRound12MDXV45LeadingOverflowProof
  TestRound12MDXV45OuterDefensiveOwnerStaysNonBlocking
  TestRound12NERVExactUntrustedBypassBoundaries
  TestRound12NERVExactUntrustedFrameAndScopeBoundaries
  TestRound12NERVExactUntrustedPairedProtocolMatrix
  TestRound12NativeReferentActivationDisposition
  TestRound12NativeReferentActivationSingleIntentMatrix
  TestRound12OuterDefensiveOwnerBoundaries
  TestRound12OuterDefensiveOwnerDoesNotLendDirectiveToAnotherInertField
  TestRound12OuterDefensiveOwnerLaterContinuationProofLossIsIncomplete
  TestRound12OuterDefensiveOwnerSuppressesInternalActivation
)

expected_round12_plugin_entries=(
  TestRound12MDXV45AuditResponsesStreamPersistsEligibleEvent
  TestRound12NERVExactUntrustedResponsesStreamDisposition
)
require_reviewed_entries ./internal/plugin "round-twelve plugin" \
  '^TestRound12[A-Za-z0-9_]*$' "${expected_round12_plugin_entries[@]}"

expected_round13_classifier_entries=(
	TestRound13AssistantMixedScriptContinuationCannotBeSuppressed
	TestRound13AssistantQuotedRestatementProofBudgetParity
	TestRound13AssistantQuotedRestatementSuffixRemainsDetectable
	TestRound13AssistantScopedRestatementCannotHideOperationalContinuation
	TestRound13AssistantScopedRestatementProofBudgetParity
	TestRound13MixedScriptSafetyObjectCannotConsumeOperationalContinuation
	TestRound13ProfiledClearNonUserSafetyFieldsAllow
  TestRound13ProfiledNegationReversalPolicyRemainsDetectable
	TestRound13ProfiledNonUserSafetyOverrideRemainsDetectable
	TestRound13SafetyPolicyNegationReversalGovernors
	TestRound13SystemQuotedRestatementSuffixProfiledParity
	TestRound13ToolPayloadSafetyFramingCannotSuppress
)

# Every classifier test-like entry visible without the consumed_evaluation build
# tag is explicitly classified. Restricted evaluation/holdout tests are not
# compiled or listed in development test/race/list modes. Any new visible test,
# fuzz target, benchmark, or example fails closed until it is reviewed here.
expected_safe_classifier_entries=(
  BenchmarkClassifier
  BenchmarkClassifierCandidateRichMaxParts
  BenchmarkClassifierLargeBenign
  BenchmarkClassifierLargePunctuation
  BenchmarkClassifierRoleAwareConversation
  BenchmarkFragmentBoundaryProfiledGroup512
  BenchmarkMetaOverrideBilingualMixed
  BenchmarkMetaOverrideLongPrompt
  BenchmarkMetaOverrideManyParts
  BenchmarkRepositoryNeutralAuthorityCatalog
  BenchmarkRound6StreamingOneMiB
  BenchmarkRound6StreamingScale
  BenchmarkStreamingDefensiveQuotedReviewFrameSignals
  FuzzDefensiveQuotedSampleBoundary
  FuzzClassifier
  FuzzMetaOverrideClausePermutation
  FuzzMetaOverrideEncodingAndPartSplit
  FuzzRound6StreamingChunkAndRoleBoundaries
  TestAnalyzeDirectivesHandlesInternalInvalidRuneBoundary
  TestAnalyzeDoesNotReturnPromptFragments
  TestAssistantClosedQuoteCannotHideNewOperationalSentence
  TestAssistantOperationalTextInsideClosedQuoteRemainsInert
  TestAssistantQuoteScopeCannotHideNewOperationalTurn
  TestAssistantRefusalMayQuoteCoordinatedAttackInertly
  TestAssistantTrailingQuoteCannotLaunderOperationalRestatement
  TestAssistantUnquotedRestatementCannotHideNewOperationalSentence
  TestAssistantUnrelatedQuoteCannotLaunderOperationalRestatement
  TestAuthorizationAloneDoesNotOverrideProtectedAbuse
  TestBalancedCorpusMetrics
  TestBehaviorGraphCoversEightCyberAbuseCategories
  TestBenignAuthorizationContextCarriesAcrossParts
  TestBilingualSemanticAndCuratedTypoTaxonomy
  TestClassifierAdversarialPerformanceAcceptance
  TestClassifierAllowsExplicitBenignSecurityContexts
  TestClassifierBlocksTerseOperationalAbuse
  TestClassifierCombinesPartsWithoutKeywordInflation
  TestClassifierConcurrentAnalyze
  TestClassifierDirectiveAllocationAcceptance
  TestClassifierHighRiskOperationalPrompts
  TestClassifierNeverBlocksOnOneEvidenceGroup
  TestClassifierNFKCAndModeSemantics
  TestClassifierNormalizesCommonHomoglyphs
  TestClassifierPerformanceAcceptance
  TestClassifierPolicyControlsContextAndAuthorization
  TestClassifierPolicyIdentity
  TestClassifierPolicySourceInventoryClosure
  TestClassifierRepeatedConcurrencyAndResourceSanity
  TestCommonPastTenseOperationalAbuse
  TestCompactRuleIntentFirstRunePreflightPreservesObfuscatedMatches
  TestCompactEvidenceDoesNotCrossParts
	TestCompactFragmentIndependentLexemeIsExactAndAllocationFree
  TestCompactMatcherHandlesUnderscoresAndShortLiterals
  TestCompactMatcherPreservesEnglishWordBoundaries
  TestContextLabelDoesNotOverrideOperationalRealTarget
  TestContextLabelsCannotCoverImperativeAbuse
  TestContextPolicyFlagsAreIndependentlyApplied
  TestControlWeakeningLanguageIsNotDefensiveContext
  TestCredentialObjectFallbackRequiresOperationalTargetAndEvasion
  TestCrossCategoryMaliciousGoalThenImplementationFollowUp
  TestCuratedTyposDoNotBecomeSingleSignalBlocks
  TestDefensiveQuotedCredentialReviewBoundary
  TestDefensiveQuotedCredentialReviewCannotHideSemanticPrefix
  TestDefensiveQuotedCredentialReviewFailsClosed
  TestDefensiveQuotedCredentialReviewFollowUps
  TestDefensiveQuotedCredentialReviewPriorProofBudgetFailsClosed
  TestDefensiveQuotedCredentialReviewPriorProofPerformanceAcceptance
  TestDefensiveQuotedCredentialReviewReferentialImplementationFollowUps
  TestDefensiveQuotedCredentialReviewStreamingReferentialFollowUps
  TestDefensiveQuotedCredentialReviewStreamingRepeatedFields
  TestDefensiveQuotedReviewCrossWindowFollowUpNeverSilentlyAllows
  TestDefensiveQuotedReviewLongStreamingReferentialFollowUps
  TestDefensiveQuotedReviewNegatedReferentRemainsInert
  TestDefensiveQuotedReviewReactivationPreservesDirectReferentResult
  TestDefensiveQuotedReviewReferentClassificationChargesWindowBudget
  TestDefensiveMaintenanceLabelDoesNotLaunderOperationalAbuse
  TestDefensiveMaintenanceRequestsRemainUsable
  TestFirstPartySecurityEvidenceToolingRemainsUsable
  TestDevelopmentAuthorizationCannotOverrideConflictingHarm
  TestDevelopmentCategorySpecificityMatrix
  TestDevelopmentContextPolarityDoesNotReverseRisk
  TestDevelopmentEnglishBoundariesAndSharedPhrasesDoNotInflate
  TestDevelopmentLegitimateWorkflowCannotLaunderExplicitHarm
  TestDevelopmentMinimumContrastPairs
  TestDevelopmentPriorTargetConflictInvalidatesCarriedAuthorization
  TestDevelopmentRound2BenignPurposeControls
  TestDevelopmentRound2NaturalOperationalIntent
  TestDevelopmentRound2TelemetryRestorationDoesNotHideReactivation
  TestDevelopmentRound2NegationAndPurposeScope
  TestDevelopmentRound3LegitimateOutcomeControls
  TestDevelopmentRound3OutcomeOrientedAbuse
  TestDevelopmentRound3ThreeTurnOperationPlans
  TestDevelopmentRound4BalancedSemanticMatrix
  TestDevelopmentSemanticBoundaryAndEvidenceOwnership
  TestDevelopmentSemanticCompositionDoesNotCrossDirectiveClauses
  TestDirectiveClauseOverflowCompositionRetainsOmittedContradiction
  TestDirectiveClauseOverflowCompositionRetainsOmittedCoreContradiction
  TestDirectiveClauseOverflowContradictionIsScopedToProviderPair
	TestDirectiveClauseDifferentProviderActiveCompositionBlocks
	TestDirectiveClauseProviderPairFinalRegressions
  TestDirectiveClauseOverflowPerformanceBoundary
  TestDirectiveClauseOverflowPreservesCompleteProhibition
  TestDirectiveClauseOverflowPreservesMaliciousCategoryTail
  TestExfiltrationNaturalParaphrases
  TestExplicitNoPermissionClearsLabContext
  TestExplicitPolicyDraftIsNotTreatedAsOperationalAbuse
  TestFindingOriginKeepsUserOnlyMultiTurnComposition
  TestFindingOriginMixedUserLikeCompositionRemainsUntrusted
  TestFindingOriginPrefersIndependentTrustedUserOnExactTie
  TestFindingOriginSurvivesStreamingCompatOver64Segments
  TestFindingOriginSurvivesLongStreamingFieldAndClearsWhenIncomplete
  TestFindingOriginTracksWinningRoleAndProvenance
  TestFragmentBoundaryBatchNewlineParity
	TestFragmentBoundaryDiscourseConnectorCannotHideDirective
  TestFragmentBoundaryDoesNotCrossInterleavedPhysicalOwner
  TestFragmentBoundaryDoesNotCrossLogicalOwners
  TestFragmentBoundaryDoesNotJoinPunctuatedIndependentSentences
  TestFragmentBoundaryFiveByFiveNewlineBatchStreamingParity
  TestFragmentBoundaryNormalizationRejectsInternalIndependentLexemes
  TestFragmentBoundaryNormalizationRequiresProvenPartReconstruction
  TestFragmentBoundaryOverlongDefensiveOwnerRemainsNonBlocking
  TestFragmentBoundaryProviderAdjacentOrdinaryBlocksRemainIndependent
  TestFragmentBoundaryProviderContentBlocksBeyondFragmentLimitParity
  TestFragmentBoundaryProviderContentBlocksParity
  TestFragmentBoundaryProviderLargeOrdinaryGroupRemainsIndependent
  TestFragmentBoundaryProviderPrecedingDefensiveOwnerRemainsNonBlocking
  TestFragmentBoundaryReconstructionRejectsLargePartRuns
  TestFragmentBoundaryReconstructionUsesOnlyAcceptedBoundaries
  TestFragmentBoundaryScanSessionSameFieldChunks
  TestFragmentBoundaryStreamingKeepsOriginalGroupWinner
  TestHardThresholdBlocksEveryEnabledMode
  TestImplementationFollowUpAndRefusalScope
  TestIndependentExecutionTailASCIISinglePassPreservesTransitions
  TestLegitimateWorkflowScopeDoesNotHideHostileCredentialOrEncryptionGoals
  TestMaliciousSystemPolicyCannotNegateRefusalInsteadOfAbuse
  TestMatcherHandlesASCIIEvidenceAdjacentToChinese
  TestMetaOverrideAcrossAdjacentTurnsAndObfuscation
  TestMetaOverrideAmplifiesCyberAbuseWithoutReplacingTaxonomy
  TestMetaOverrideAmplifiesOnlyTheWinningOrdinaryCandidate
  TestMetaOverrideClauseBudgetPerformance
  TestMetaOverrideClauseBudgetRejectsDefensiveCredit
  TestMetaOverrideConnectorFloodAllocationBound
  TestMetaOverrideDefensiveAnalysisAndQuotedMaterialAllow
  TestMetaOverrideDirectDisclosureRequestAudits
  TestMetaOverrideDoesNotPromoteWeakOrdinaryCandidates
  TestMetaOverrideLabelsRemainControlSignalsWithoutBaseBehavior
  TestMetaOverrideNinthLinkedPartRetainsEarlierFamilies
  TestMetaOverrideReconstructsIsolatedUserSegments
  TestMetaOverrideRoleAndToolProvenance
  TestMetaOverrideSingleDisclosurePhraseDoesNotAccumulateRisk
  TestMetaOverrideStrongControlPlaneAttacksAreAuditOnly
  TestMetaOverrideStillAmplifiesQualifiedOrBalancedAttack
  TestMultiTurnSafetyFramingCannotCoverImplementation
  TestNegationPhraseCannotBypassCurrentOperationalAbuse
  TestNegativeAuthorizationClearsLabLaundering
  TestNoPermissionIssuesDoesNotClearAuthorizedLabContext
  TestNoRansomwareCrossMatchForCredentialRequest
  TestNormalizationAndPartBudgetsAreBounded
  TestNormalizedRuneBufferScrubsPromptDerivedStorage
  TestOfflineForensicsSafetyClauseCannotWashOperationalOverride
  TestOversizedPotentialActionRunePreflightPreservesCompactFallback
  TestPriorDefensiveContextDoesNotSanitizeCurrentAbuse
  TestPriorNegatedPolicyDoesNotPoisonImplementationFollowUp
  TestPriorPolicyTermsDoNotPoisonUnrelatedCurrentTurn
  TestPriorSafetyContextDoesNotSanitizeLaterAbuse
  TestProtectedAuthorizationAcrossPartsDoesNotBypass
  TestProfiledMetadataIndexSentinelsDoNotOptLegacySlicesIn
  TestProfiledMetadataNormalizesMixedLegacyIndexesWithoutMutatingCaller
  TestProfiledSameScopeIndependentFieldIncompleteBatchStreamingParity
  TestProfiledMetadataUnscopedLegacyAssistantCannotBecomeHistoricalReferent
  TestQualifiedNeutralCoreBecomesOperationalAbuse
  TestResultJSONOmitsZeroCoverage
  TestRoleAwareClassifierNeverSilentlyAgesOutAbuse
  TestRoleAwareClearSafetyContentIsNotAttributedAsIntent
  TestRoleAwareClosedQuotedNonExecutionHistoryRemainsInert
  TestRoleAwareNonUserExamplesDoNotPolluteSafeUser
  TestRoleAwareNonUserSafetyExampleDoesNotSupplyUserFollowUpIntent
  TestRoleAwareOnlyCarriesGenuinelyAdjacentUserFollowUp
  TestRoleAwareProviderRefusalWithBenignToolPayloadAllows
  TestRoleAwareRefusedHistoricalAttackAllowsNarrowSafetyMaintenance
  TestRoleAwareRefusedHistoricalAttackReactivatesOnExecutionFollowUp
  TestRoleAwareSafetyFramingWithBenignContinuationAllows
  TestRoleAwareTruncatedDefensiveReconstructionKeepsWrapperFinding
  TestRoleAwareUnknownProvenanceUsesConservativeFallback
  TestRoleAwareUserFollowUpSkipsAssistantRefusal
  TestRoleAwareWrapperOnlyCapsProvenanceButKeepsRolelessConservative
  TestRound5AgenticEscalationAmplifiesButDoesNotReplaceBaseTaxonomy
	TestRound5AdjacentCompactIntentNegationFailsClosed
  TestRound5AdjacentNegationCandidateFloodFailsClosed
  TestRound5AdjacentNegationCandidateFloodPerformanceAcceptance
	TestRound5AdjacentOverflowPreservesAllMatchedCores
  TestRound5AdjacentPartsNegationReversalCannotHideAbuse
  TestRound5AdjacentPartsNegationReversalSurvivesTrailingParts
  TestRound5AdjacentReversalUsesConfiguredHardBlockThreshold
  TestRound5AdjacentUserSegmentsNegationReversalCannotHideAbuse
  TestRound5CoordinatedCrossCategoryProhibitionsRemainBenign
  TestRound5CrossCategoryNegationDoesNotCoverOperationalTail
	TestRound5DirectiveBoundaryRunsPreserveSentenceBreaks
	TestRound5DirectiveBudgetCountsRiskRelevantClauses
	TestRound5EarlierLiteralNegationCannotHideLaterCompactClause
  TestRound5LargeAdjacentNegationReconstructionFailsClosed
	TestRound5LongNegationReversalBridgeFailsActive
	TestRound5NegatedProhibitionModalBridgeFailsActive
	TestRound5MetaOverrideBenignNearNeighborsAllow
  TestRound5MetaOverrideBilingualFamilies
  TestRound5MetaOverrideDefensiveQuotedSamplesRemainInert
  TestRound5MetaOverrideDefensiveTailCannotAuthorizeExecution
  TestRound5MetaOverrideFamiliesProduceFixedEvidence
  TestRound5MetaOverridePerformanceAcceptance
  TestRound5MalformedUTF8DirectiveBoundariesConsumeDecodedWidth
  TestRound5NegationCannotHideLaterActiveIntent
  TestRound5PersistentBlockSurvivesIncidentalLowScoreTaxonomyTerms
  TestRound5PersistentInstructionInjectionAcrossLinkedUserSegments
  TestRound5PersistentInstructionInjectionBlocksOnlyActiveSafetyOverride
  TestRound5RepositoryNeutralAuthorityVariants
  TestRound5RepositoryNeutralDomainCatalogStaysWrapperOnly
  TestRound5RefusalScopeOutputAndCompoundIntentHardening
  TestRound5NegationReversalKeepsTrueProhibitionsBenign
	TestRound5NormalizedContractionsRemainNegationReversals
	TestRound5RepeatedIntentYInflectionsFailActive
	TestRound5UnrelatedPassiveNegationCannotLaunderMetaTarget
  TestRound5UnrelatedSignalsDoNotPolluteMetaTail
  TestRound5WrapperAuditSurvivesIncidentalLowScoreTaxonomyTerms
  TestRound6DefaultBudgetCoversMaximumLogicalFieldFragmentation
  TestRound6HardLogicalFieldBoundHasCompleteBudget
  TestRound6IncompleteClearsUnverifiedFinding
  TestRound6NormalizeBytesMatchesStringNormalization
  TestRound6NormalizeBytesRejectsInvalidUTF8
  TestRound6RequiredChunkOverlapFitsConfigurationBudget
  TestRound6SingleWindowHasNoBoundaryReconstruction
  TestRound6StreamingClosedSafetyQuoteDiscardsProvisionalFinding
  TestRound6StreamingClosedSafetyQuoteTailStaysInertAcrossNextUserField
  TestRound6StreamingCompactMatcherSurvivesMoreThanOverlapSeparators
  TestRound6StreamingControlPairDoesNotCarryBaseBehaviorAcrossRoles
  TestRound6StreamingNonUserWrapperCapPreservesLaterBaseBehavior
  TestRound6StreamingCoverageReasonsAreSeparateFromProofBudgets
  TestRound6StreamingCrossWindowLiteralAndNFKC
  TestRound6StreamingCrossWindowPriorAndReferentialFollowUpBecomesIncomplete
  TestRound6StreamingCrossWindowQuotedReviewIsExplicitlyIncomplete
  TestRound6StreamingDoesNotJoinDifferentRoleFields
  TestRound6StreamingInternalChunksDoNotConsumeLogicalPartBudget
  TestRound6StreamingInvalidOrderIsOperationalError
  TestRound6StreamingLateHarmConflictBecomesIncomplete
  TestRound6StreamingLateUnnegatedSyntheticIntentBecomesIncomplete
  TestRound6StreamingLongAssistantQuotedRefusalRemainsInert
  TestRound6StreamingLongAssistantTailDoesNotComposeBaseBehaviorWithUser
  TestRound6StreamingLongPriorUserCoreAndFollowUpBecomesIncomplete
  TestRound6StreamingMappedToolControlRemainsAuditOnly
  TestRound6StreamingMalformedCrossWindowQuotedReviewCannotEraseHardBlock
  TestRound6StreamingNegationAcrossWindowRemainsInert
  TestRound6StreamingNegatedSyntheticIntentRemainsComplete
  TestRound6StreamingPreservesBoundedRoleCompositionsAfterSixtyFourFields
  TestRound6StreamingPreservesShortRoleAwareDecisions
  TestRound6StreamingPreservesThreeTurnRoleSemanticsAfterSixtyFourFields
  TestRound6StreamingProcessesAllSixtyFiveFields
  TestRound6StreamingPriorSafetyWindowDoesNotLaunderLaterInstruction
  TestRound6StreamingProvenLongQuotedReviewRetainsNoPromptBytes
  TestRound6StreamingQuotedSafetyPrefixDoesNotLaunderEarlierInstruction
  TestRound6StreamingSplitSyntheticCoreBecomesIncomplete
  TestRound6StreamingSplitSyntheticQualifiersBecomeIncomplete
  TestRound6StreamingStrictSplitSyntheticCoreBecomesIncomplete
  TestRound6StreamingStrictSplitWrapperOnlyMetaRemainsComplete
  TestRound6StreamingSyntheticFactsStayInsideLogicalField
  TestRound6StreamingSyntheticSafetyQuoteTransactions
  TestRound6StreamingUnclosedSafetyQuoteCommitsProvisionalFinding
  TestRound6StreamingUnclosedSafetyQuoteHarmConflictBecomesIncomplete
  TestRound6StreamingUnquotedTailAfterSafetyQuoteLinksNextUserField
  TestRound6StreamingUnrelatedMetaWindowsDoNotCompose
  TestRound6StreamingUnknownLongFieldRetainsBoundedRiskFacts
  TestRound6StreamingUnknownPersistentControlPlaneSplitFailsClosed
  TestRound6StreamingUnknownLongBenignFieldDoesNotPromoteSingleRisk
  TestRound6StreamingRiskAfterLongBenignBoundaryFailsClosed
  TestRound6StreamingRepeatedRiskAfterContextBoundaryFailsClosed
  TestRound6StreamingUnknownToolPayloadClearsRiskBoundary
  TestRound6StreamingKnownRoleClearsUnknownRiskFacts
  TestRound6StreamingLongUnknownBoundaryClearsUserComposition
  TestRound6StreamingPersistentControlPlaneAcrossWindowsBecomesIncomplete
  TestSafetyLabelsCannotWashOutOperationalAbuse
  TestSameCategoryEvidenceCompositionIsScopedAndConservative
  TestScopedAuthorizationNamingActionCarriesForNonProtectedCategory
  TestScopedExplanationAndConceptualPhrasesAreAllowed
  TestScopedNegationAllowsProhibitionsButNotNegationBait
  TestStreamingMetaOverridePromotionRequiresQualifiedOrBalancedOrdinaryRisk
  TestStreamingRefusedHistoricalAttackSafetyMaintenanceBoundary
  TestStructuredQuoteSyntaxFastPathPreservesEveryDelimiter
  TestSystemClosedQuoteCannotHideNewOperationalSentence
  TestUnrelatedPriorQualifierDoesNotInflateCurrentBenignAnalysis
  TestUnscopedPriorLabDoesNotCoverRealTarget
  TestUntrustedPartsFallbackScansOlderPartsAndReportsCapacity
  TestValidUTF8PrefixHandlesInteriorInvalidByte
  TestWrapperBaseBehaviorMinimalContrasts
  TestWrapperOnlyNeverBlocksAnyMode
)
expected_safe_classifier_entries+=("${expected_round8_classifier_entries[@]}")
expected_safe_classifier_entries+=("${expected_round9_classifier_entries[@]}")
expected_safe_classifier_entries+=("${expected_round10_classifier_entries[@]}")
expected_safe_classifier_entries+=("${expected_round12_classifier_entries[@]}")
expected_safe_classifier_entries+=("${expected_round13_classifier_entries[@]}")
declare -A safe_seen=()
for name in "${expected_safe_classifier_entries[@]}"; do
	if [[ -v safe_seen["$name"] ]]; then
    printf 'duplicate classifier allowlist entry: %s\n' "$name" >&2
    exit 1
  fi
  safe_seen["$name"]=0
done

listed_test_output="$(
  "$go_bin" test -tags="$test_tags" ./internal/classifier \
    -list '^(Test|Fuzz|Benchmark|Example)'
)"
mapfile -t listed_tests <<<"$listed_test_output"
for name in "${listed_tests[@]}"; do
  [[ "$name" =~ ^(Test|Fuzz|Benchmark|Example)[A-Za-z0-9_]*$ ]] || continue
  if [[ -v safe_seen["$name"] ]]; then
    safe_seen["$name"]=1
  else
    printf 'unclassified classifier test-like entry: %s\n' "$name" >&2
    exit 1
  fi
done

for name in "${expected_safe_classifier_entries[@]}"; do
  if [[ "${safe_seen[$name]}" != 1 ]]; then
    printf 'required safe classifier entry is missing: %s\n' "$name" >&2
    exit 1
  fi
done

safe_pattern="$(join_regex "${expected_safe_classifier_entries[@]}")"
boundary_pattern="$(join_regex \
  TestEvaluationV10Integrity \
  TestEvaluationV10HistoricalSnapshotRecordIntegrity \
  TestEvaluationV10ConsumedRerunRejected)"

case "$mode" in
  list)
    "$go_bin" -C "$round9_counted_mock_module" list . >/dev/null
    round8_entry_count=$((
      ${#expected_round8_audit_entries[@]} +
      ${#expected_round8_extract_entries[@]} +
      ${#expected_round8_plugin_entries[@]} +
      ${#expected_round8_classifier_entries[@]}
    ))
    round9_entry_count=$((
      ${#expected_round9_audit_entries[@]} +
      ${#expected_round9_extract_entries[@]} +
      ${#expected_round9_plugin_entries[@]} +
      ${#expected_round9_classifier_entries[@]}
    ))
    round10_entry_count=$((
      ${#expected_round10_extract_entries[@]} +
      ${#expected_round10_plugin_entries[@]} +
      ${#expected_round10_classifier_entries[@]}
    ))
    round12_entry_count=$((
      ${#expected_round12_classifier_entries[@]} +
      ${#expected_round12_plugin_entries[@]}
    ))
    printf 'Round6 safe development boundary: packages=%d classifier_entries=%d round8_entries=%d round9_entries=%d round10_entries=%d round12_entries=%d\n' \
      "${#safe_packages[@]}" "${#expected_safe_classifier_entries[@]}" \
      "$round8_entry_count" "$round9_entry_count" "$round10_entry_count" \
      "$round12_entry_count"
    ;;
  test)
    "$go_bin" test -tags="$test_tags" -count=1 "${safe_packages[@]}"
    "$go_bin" test -tags="$test_tags" -count=1 -run="$safe_pattern" ./internal/classifier
    "$go_bin" -C "$round9_counted_mock_module" test -count=1 .
    ;;
	race)
		CGO_ENABLED=1 "$go_bin" test -race -timeout=20m -tags="$test_tags" -count=1 "${safe_packages[@]}"
		CGO_ENABLED=1 "$go_bin" test -race -timeout=20m -tags="$test_tags" -count=1 -run="$safe_pattern" ./internal/classifier
    CGO_ENABLED=1 "$go_bin" -C "$round9_counted_mock_module" test -race -count=1 .
    ;;
  boundary)
    "$go_bin" test -tags="$test_tags,consumed_evaluation" -count=1 -v -run="$boundary_pattern" ./internal/classifier
    ;;
  *)
	printf 'usage: %s list|test|race|boundary\n' "${0##*/}" >&2
    exit 2
    ;;
esac
